using Markdig.Renderers.Html;
using Markdig.Syntax;
using Markdig.Syntax.Inlines;

namespace HtmlUtility.UnitTests.Helpers;

public static partial class ExampleMarkdown1
{
    class MarkdownElements
    {
        internal MarkdownDocument Document { get; init; }

        private HeadingBlock? _element0;
        internal HeadingBlock Element0 => _element0 ??= (HeadingBlock)Document[0];
        private HtmlAttributes? _element0_Attributes;
        internal HtmlAttributes Element0_Attributes => _element0_Attributes ?? Element0.GetAttributes();
        private LiteralInline? _element0_0;
        internal LiteralInline Element0_0 => _element0_0 ??= (LiteralInline)Element0.Inline!.FirstChild!;
        private ParagraphBlock? _element1;
        internal ParagraphBlock Element1 => _element1 ??= (ParagraphBlock)Document[1];
        private LinkInline? _element1_0;
        internal LinkInline Element1_0 => _element1_0 ??= (LinkInline)Element1.Inline!.FirstChild!;
        private LiteralInline? _element1_0_0;
        internal LiteralInline Element1_0_0 => _element1_0_0 ??= (LiteralInline)Element1_0.FirstChild!;
        private ParagraphBlock? _element2;
        internal ParagraphBlock Element2 => _element2 ??= (ParagraphBlock)Document[2];
        private LiteralInline? _element2_0;
        internal LiteralInline Element2_0 => _element2_0 ??= (LiteralInline)Element2.Inline!.FirstChild!;
        private LineBreakInline? _element2_1;
        internal LineBreakInline Element2_1 => _element2_1 ??= (LineBreakInline)Element2_0.NextSibling!;
        private LiteralInline? _element2_2;
        internal LiteralInline Element2_2 => _element2_2 ??= (LiteralInline)Element2.Inline!.LastChild!;
        private ListBlock? _element3;
        internal ListBlock Element3 => _element3 ??= (ListBlock)Document[3];
        private HtmlAttributes? _element3_Attributes;
        internal HtmlAttributes Element3_Attributes => _element3_Attributes ?? Element3.GetAttributes();
        private ListItemBlock? _element3_0;
        internal ListItemBlock Element3_0 => _element3_0 ??= (ListItemBlock)Element3[0];
        private HtmlAttributes? _element3_0_Attributes;
        internal HtmlAttributes Element3_0_Attributes => _element3_0_Attributes ?? Element3_0.GetAttributes();
        private ParagraphBlock? _element3_0_0;
        internal ParagraphBlock Element3_0_0 => _element3_0_0 ??= (ParagraphBlock)Element3_0[0];
        private Markdig.Extensions.TaskLists.TaskList? _element3_0_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element3_0_0_0 => _element3_0_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element3_0_0.Inline!.FirstChild!;
        private LiteralInline? _element3_0_0_1;
        internal LiteralInline Element3_0_0_1 => _element3_0_0_1 ??= (LiteralInline)Element3_0_0.Inline!.LastChild!;
        private ListItemBlock? _element3_1;
        internal ListItemBlock Element3_1 => _element3_1 ??= (ListItemBlock)Element3[1];
        private HtmlAttributes? _element3_1_Attributes;
        internal HtmlAttributes Element3_1_Attributes => _element3_1_Attributes ?? Element3_1.GetAttributes();
        private ParagraphBlock? _element3_1_0;
        internal ParagraphBlock Element3_1_0 => _element3_1_0 ??= (ParagraphBlock)Element3_1[0];
        private Markdig.Extensions.TaskLists.TaskList? _element3_1_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element3_1_0_0 => _element3_1_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element3_1_0.Inline!.FirstChild!;
        private LiteralInline? _element3_1_0_1;
        internal LiteralInline Element3_1_0_1 => _element3_1_0_1 ??= (LiteralInline)Element3_1_0.Inline!.LastChild!;
        private ListItemBlock? _element3_2;
        internal ListItemBlock Element3_2 => _element3_2 ??= (ListItemBlock)Element3[2];
        private ParagraphBlock? _element3_2_0;
        internal ParagraphBlock Element3_2_0 => _element3_2_0 ??= (ParagraphBlock)Element3_2[0];
        private LiteralInline? _element3_2_0_0;
        internal LiteralInline Element3_2_0_0 => _element3_2_0_0 ??= (LiteralInline)Element3_2_0.Inline!.FirstChild!;
        private ListItemBlock? _element3_3;
        internal ListItemBlock Element3_3 => _element3_3 ??= (ListItemBlock)Element3[3];
        private ParagraphBlock? _element3_3_0;
        internal ParagraphBlock Element3_3_0 => _element3_3_0 ??= (ParagraphBlock)Element3_3[0];
        private LiteralInline? _element3_3_0_0;
        internal LiteralInline Element3_3_0_0 => _element3_3_0_0 ??= (LiteralInline)Element3_3_0.Inline!.FirstChild!;
        private HeadingBlock? _element4;
        internal HeadingBlock Element4 => _element4 ??= (HeadingBlock)Document[4];
        private HtmlAttributes? _element4_Attributes;
        internal HtmlAttributes Element4_Attributes => _element4_Attributes ?? Element4.GetAttributes();
        private LiteralInline? _element4_0;
        internal LiteralInline Element4_0 => _element4_0 ??= (LiteralInline)Element4.Inline!.FirstChild!;
        private HeadingBlock? _element5;
        internal HeadingBlock Element5 => _element5 ??= (HeadingBlock)Document[5];
        private HtmlAttributes? _element5_Attributes;
        internal HtmlAttributes Element5_Attributes => _element5_Attributes ?? Element5.GetAttributes();
        private LiteralInline? _element5_0;
        internal LiteralInline Element5_0 => _element5_0 ??= (LiteralInline)Element5.Inline!.FirstChild!;
        private ParagraphBlock? _element6;
        internal ParagraphBlock Element6 => _element6 ??= (ParagraphBlock)Document[6];
        private LinkInline? _element6_0;
        internal LinkInline Element6_0 => _element6_0 ??= (LinkInline)Element6.Inline!.FirstChild!;
        private LiteralInline? _element6_0_0;
        internal LiteralInline Element6_0_0 => _element6_0_0 ??= (LiteralInline)Element6_0.FirstChild!;
        private HeadingBlock? _element7;
        internal HeadingBlock Element7 => _element7 ??= (HeadingBlock)Document[7];
        private HtmlAttributes? _element7_Attributes;
        internal HtmlAttributes Element7_Attributes => _element7_Attributes ?? Element7.GetAttributes();
        private LiteralInline? _element7_0;
        internal LiteralInline Element7_0 => _element7_0 ??= (LiteralInline)Element7.Inline!.FirstChild!;
        private ParagraphBlock? _element8;
        internal ParagraphBlock Element8 => _element8 ??= (ParagraphBlock)Document[8];
        private LinkInline? _element8_0;
        internal LinkInline Element8_0 => _element8_0 ??= (LinkInline)Element8.Inline!.FirstChild!;
        private LiteralInline? _element8_0_0;
        internal LiteralInline Element8_0_0 => _element8_0_0 ??= (LiteralInline)Element8_0.FirstChild!;
        private ParagraphBlock? _element9;
        internal ParagraphBlock Element9 => _element9 ??= (ParagraphBlock)Document[9];
        private LinkInline? _element9_0;
        internal LinkInline Element9_0 => _element9_0 ??= (LinkInline)Element9.Inline!.FirstChild!;
        private LiteralInline? _element9_0_0;
        internal LiteralInline Element9_0_0 => _element9_0_0 ??= (LiteralInline)Element9_0.FirstChild!;
        private EmphasisInline? _element9_0_1;
        internal EmphasisInline Element9_0_1 => _element9_0_1 ??= (EmphasisInline)Element9_0.LastChild!;
        private LiteralInline? _element9_0_1_0;
        internal LiteralInline Element9_0_1_0 => _element9_0_1_0 ??= (LiteralInline)Element9_0_1.FirstChild!;
        private LinkReferenceDefinitionGroup? _element10;
        internal LinkReferenceDefinitionGroup Element10 => _element10 ??= (LinkReferenceDefinitionGroup)Document[10];
        private LinkReferenceDefinition? _element10_0;
        internal LinkReferenceDefinition Element10_0 => _element10_0 ??= (LinkReferenceDefinition)Element10[0];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element10_1;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element10_1 => _element10_1 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element10[1];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element10_2;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element10_2 => _element10_2 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element10[2];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_3;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_3 => _element10_3 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[3];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_4;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_4 => _element10_4 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[4];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_5;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_5 => _element10_5 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[5];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_6;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_6 => _element10_6 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[6];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_7;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_7 => _element10_7 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[7];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_8;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_8 => _element10_8 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[8];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_9;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_9 => _element10_9 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[9];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_10;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_10 => _element10_10 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[10];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_11;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_11 => _element10_11 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[11];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_12;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_12 => _element10_12 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[12];
        private HeadingBlock? _element11;
        internal HeadingBlock Element11 => _element11 ??= (HeadingBlock)Document[11];
        private HtmlAttributes? _element11_Attributes;
        internal HtmlAttributes Element11_Attributes => _element11_Attributes ?? Element11.GetAttributes();
        private LiteralInline? _element11_0;
        internal LiteralInline Element11_0 => _element11_0 ??= (LiteralInline)Element11.Inline!.FirstChild!;
        private ParagraphBlock? _element12;
        internal ParagraphBlock Element12 => _element12 ??= (ParagraphBlock)Document[12];
        private LiteralInline? _element12_0;
        internal LiteralInline Element12_0 => _element12_0 ??= (LiteralInline)Element12.Inline!.FirstChild!;
        private CodeInline? _element12_1;
        internal CodeInline Element12_1 => _element12_1 ??= (CodeInline)Element12.Inline!.FirstChild!;
        private LiteralInline? _element12_2;
        internal LiteralInline Element12_2 => _element12_2 ??= (LiteralInline)Element12.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element12_3;
        internal Markdig.Extensions.Mathematics.MathInline Element12_3 => _element12_3 ??= (Markdig.Extensions.Mathematics.MathInline)Element12.Inline!.FirstChild!;
        private HtmlAttributes? _element12_3_Attributes;
        internal HtmlAttributes Element12_3_Attributes => _element12_3_Attributes ?? Element12_3.GetAttributes();
        private ParagraphBlock? _element13;
        internal ParagraphBlock Element13 => _element13 ??= (ParagraphBlock)Document[13];
        private LiteralInline? _element13_0;
        internal LiteralInline Element13_0 => _element13_0 ??= (LiteralInline)Element13.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element13_1;
        internal Markdig.Extensions.Mathematics.MathInline Element13_1 => _element13_1 ??= (Markdig.Extensions.Mathematics.MathInline)Element13.Inline!.FirstChild!;
        private HtmlAttributes? _element13_1_Attributes;
        internal HtmlAttributes Element13_1_Attributes => _element13_1_Attributes ?? Element13_1.GetAttributes();
        private LiteralInline? _element13_2;
        internal LiteralInline Element13_2 => _element13_2 ??= (LiteralInline)Element13.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element13_3;
        internal Markdig.Extensions.Mathematics.MathInline Element13_3 => _element13_3 ??= (Markdig.Extensions.Mathematics.MathInline)Element13.Inline!.FirstChild!;
        private HtmlAttributes? _element13_3_Attributes;
        internal HtmlAttributes Element13_3_Attributes => _element13_3_Attributes ?? Element13_3.GetAttributes();
        private ParagraphBlock? _element14;
        internal ParagraphBlock Element14 => _element14 ??= (ParagraphBlock)Document[14];
        private EmphasisInline? _element14_0;
        internal EmphasisInline Element14_0 => _element14_0 ??= (EmphasisInline)Element14.Inline!.FirstChild!;
        private LiteralInline? _element14_0_0;
        internal LiteralInline Element14_0_0 => _element14_0_0 ??= (LiteralInline)Element14_0.FirstChild!;
        private LineBreakInline? _element14_1;
        internal LineBreakInline Element14_1 => _element14_1 ??= (LineBreakInline)Element14.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element14_2;
        internal Markdig.Extensions.Mathematics.MathInline Element14_2 => _element14_2 ??= (Markdig.Extensions.Mathematics.MathInline)Element14.Inline!.FirstChild!;
        private HtmlAttributes? _element14_2_Attributes;
        internal HtmlAttributes Element14_2_Attributes => _element14_2_Attributes ?? Element14_2.GetAttributes();
        private HeadingBlock? _element15;
        internal HeadingBlock Element15 => _element15 ??= (HeadingBlock)Document[15];
        private HtmlAttributes? _element15_Attributes;
        internal HtmlAttributes Element15_Attributes => _element15_Attributes ?? Element15.GetAttributes();
        private LiteralInline? _element15_0;
        internal LiteralInline Element15_0 => _element15_0 ??= (LiteralInline)Element15.Inline!.FirstChild!;
        private Markdig.Extensions.DefinitionLists.DefinitionList? _element16;
        internal Markdig.Extensions.DefinitionLists.DefinitionList Element16 => _element16 ??= (Markdig.Extensions.DefinitionLists.DefinitionList)Document[16];
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element16_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element16_0 => _element16_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element16[0];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element16_0_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element16_0_0 => _element16_0_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element16_0[0];
        private LiteralInline? _element16_0_0_0;
        internal LiteralInline Element16_0_0_0 => _element16_0_0_0 ??= (LiteralInline)Element16_0_0.Inline!.FirstChild!;
        private ParagraphBlock? _element16_0_1;
        internal ParagraphBlock Element16_0_1 => _element16_0_1 ??= (ParagraphBlock)Element16_0[1];
        private LiteralInline? _element16_0_1_0;
        internal LiteralInline Element16_0_1_0 => _element16_0_1_0 ??= (LiteralInline)Element16_0_1.Inline!.FirstChild!;
        private LineBreakInline? _element16_0_1_1;
        internal LineBreakInline Element16_0_1_1 => _element16_0_1_1 ??= (LineBreakInline)Element16_0_1.Inline!.FirstChild!;
        private LiteralInline? _element16_0_1_2;
        internal LiteralInline Element16_0_1_2 => _element16_0_1_2 ??= (LiteralInline)Element16_0_1.Inline!.FirstChild!;
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element16_1;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element16_1 => _element16_1 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element16[1];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element16_1_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element16_1_0 => _element16_1_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element16_1[0];
        private LiteralInline? _element16_1_0_0;
        internal LiteralInline Element16_1_0_0 => _element16_1_0_0 ??= (LiteralInline)Element16_1_0.Inline!.FirstChild!;
        private ParagraphBlock? _element16_1_1;
        internal ParagraphBlock Element16_1_1 => _element16_1_1 ??= (ParagraphBlock)Element16_1[1];
        private LiteralInline? _element16_1_1_0;
        internal LiteralInline Element16_1_1_0 => _element16_1_1_0 ??= (LiteralInline)Element16_1_1.Inline!.FirstChild!;
        private HeadingBlock? _element17;
        internal HeadingBlock Element17 => _element17 ??= (HeadingBlock)Document[17];
        private HtmlAttributes? _element17_Attributes;
        internal HtmlAttributes Element17_Attributes => _element17_Attributes ?? Element17.GetAttributes();
        private LiteralInline? _element17_0;
        internal LiteralInline Element17_0 => _element17_0 ??= (LiteralInline)Element17.Inline!.FirstChild!;
        private ParagraphBlock? _element18;
        internal ParagraphBlock Element18 => _element18 ??= (ParagraphBlock)Document[18];
        private LiteralInline? _element18_0;
        internal LiteralInline Element18_0 => _element18_0 ??= (LiteralInline)Element18.Inline!.FirstChild!;
        private CodeInline? _element18_1;
        internal CodeInline Element18_1 => _element18_1 ??= (CodeInline)Element18.Inline!.FirstChild!;
        private LiteralInline? _element18_2;
        internal LiteralInline Element18_2 => _element18_2 ??= (LiteralInline)Element18.Inline!.FirstChild!;
        private FencedCodeBlock? _element19;
        internal FencedCodeBlock Element19 => _element19 ??= (FencedCodeBlock)Document[19];
        private HtmlAttributes? _element19_Attributes;
        internal HtmlAttributes Element19_Attributes => _element19_Attributes ?? Element19.GetAttributes();
        private FencedCodeBlock? _element20;
        internal FencedCodeBlock Element20 => _element20 ??= (FencedCodeBlock)Document[20];
        private HtmlAttributes? _element20_Attributes;
        internal HtmlAttributes Element20_Attributes => _element20_Attributes ?? Element20.GetAttributes();
        private HeadingBlock? _element21;
        internal HeadingBlock Element21 => _element21 ??= (HeadingBlock)Document[21];
        private HtmlAttributes? _element21_Attributes;
        internal HtmlAttributes Element21_Attributes => _element21_Attributes ?? Element21.GetAttributes();
        private LiteralInline? _element21_0;
        internal LiteralInline Element21_0 => _element21_0 ??= (LiteralInline)Element21.Inline!.FirstChild!;
        private ParagraphBlock? _element22;
        internal ParagraphBlock Element22 => _element22 ??= (ParagraphBlock)Document[22];
        private LiteralInline? _element22_0;
        internal LiteralInline Element22_0 => _element22_0 ??= (LiteralInline)Element22.Inline!.FirstChild!;
        private LineBreakInline? _element22_1;
        internal LineBreakInline Element22_1 => _element22_1 ??= (LineBreakInline)Element22.Inline!.FirstChild!;
        private HtmlAttributes? _element22_1_Attributes;
        internal HtmlAttributes Element22_1_Attributes => _element22_1_Attributes ?? Element22_1.GetAttributes();
        private HeadingBlock? _element23;
        internal HeadingBlock Element23 => _element23 ??= (HeadingBlock)Document[23];
        private HtmlAttributes? _element23_Attributes;
        internal HtmlAttributes Element23_Attributes => _element23_Attributes ?? Element23.GetAttributes();
        private LiteralInline? _element23_0;
        internal LiteralInline Element23_0 => _element23_0 ??= (LiteralInline)Element23.Inline!.FirstChild!;
        private ParagraphBlock? _element24;
        internal ParagraphBlock Element24 => _element24 ??= (ParagraphBlock)Document[24];
        private LiteralInline? _element24_0;
        internal LiteralInline Element24_0 => _element24_0 ??= (LiteralInline)Element24.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element24_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element24_1 => _element24_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element24.Inline!.FirstChild!;
        private LiteralInline? _element24_2;
        internal LiteralInline Element24_2 => _element24_2 ??= (LiteralInline)Element24.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element24_3;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element24_3 => _element24_3 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element24.Inline!.FirstChild!;
        private LiteralInline? _element24_4;
        internal LiteralInline Element24_4 => _element24_4 ??= (LiteralInline)Element24.Inline!.FirstChild!;
        private HeadingBlock? _element25;
        internal HeadingBlock Element25 => _element25 ??= (HeadingBlock)Document[25];
        private HtmlAttributes? _element25_Attributes;
        internal HtmlAttributes Element25_Attributes => _element25_Attributes ?? Element25.GetAttributes();
        private LiteralInline? _element25_0;
        internal LiteralInline Element25_0 => _element25_0 ??= (LiteralInline)Element25.Inline!.FirstChild!;
        private ParagraphBlock? _element26;
        internal ParagraphBlock Element26 => _element26 ??= (ParagraphBlock)Document[26];
        private LiteralInline? _element26_0;
        internal LiteralInline Element26_0 => _element26_0 ??= (LiteralInline)Element26.Inline!.FirstChild!;
        private ParagraphBlock? _element27;
        internal ParagraphBlock Element27 => _element27 ??= (ParagraphBlock)Document[27];
        private LiteralInline? _element27_0;
        internal LiteralInline Element27_0 => _element27_0 ??= (LiteralInline)Element27.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteGroup? _element28;
        internal Markdig.Extensions.Footnotes.FootnoteGroup Element28 => _element28 ??= (Markdig.Extensions.Footnotes.FootnoteGroup)Document[28];
        private Markdig.Extensions.Footnotes.Footnote? _element28_0;
        internal Markdig.Extensions.Footnotes.Footnote Element28_0 => _element28_0 ??= (Markdig.Extensions.Footnotes.Footnote)Element28[0];
        private ParagraphBlock? _element28_0_0;
        internal ParagraphBlock Element28_0_0 => _element28_0_0 ??= (ParagraphBlock)Element28_0[0];
        private LiteralInline? _element28_0_0_0;
        internal LiteralInline Element28_0_0_0 => _element28_0_0_0 ??= (LiteralInline)Element28_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element28_0_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element28_0_0_1 => _element28_0_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element28_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.Footnote? _element28_1;
        internal Markdig.Extensions.Footnotes.Footnote Element28_1 => _element28_1 ??= (Markdig.Extensions.Footnotes.Footnote)Element28[1];
        private ParagraphBlock? _element28_1_0;
        internal ParagraphBlock Element28_1_0 => _element28_1_0 ??= (ParagraphBlock)Element28_1[0];
        private LiteralInline? _element28_1_0_0;
        internal LiteralInline Element28_1_0_0 => _element28_1_0_0 ??= (LiteralInline)Element28_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element28_1_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element28_1_0_1 => _element28_1_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element28_1_0.Inline!.FirstChild!;
        
        internal MarkdownElements(MarkdownDocument markdownDocument)
        {
            Document = markdownDocument;
        }
    }
}