using Markdig.Renderers.Html;
using Markdig.Syntax;
using Markdig.Syntax.Inlines;

namespace HtmlUtility.UnitTests.Helpers;

public static partial class ExampleMarkdown1
{
    class MarkdownElements
    {
        internal MarkdownDocument Document { get; init; }

        private HeadingBlock? _element0;
        internal HeadingBlock Element0 => _element0 ??= (HeadingBlock)Document[0];
        private HtmlAttributes? _element0_Attributes;
        internal HtmlAttributes Element0_Attributes => _element0_Attributes ?? Element0.GetAttributes();
        private LiteralInline? _element0_0;
        internal LiteralInline Element0_0 => _element0_0 ??= (LiteralInline)Element0.Inline!.FirstChild!;
        private HtmlBlock? _element1;
        internal HtmlBlock Element1 => _element1 ??= (HtmlBlock)Document[1];
        private ParagraphBlock? _element2;
        internal ParagraphBlock Element2 => _element2 ??= (ParagraphBlock)Document[2];
        private LiteralInline? _element2_0;
        internal LiteralInline Element2_0 => _element2_0 ??= (LiteralInline)Element2.Inline!.FirstChild!;
        private ParagraphBlock? _element3;
        internal ParagraphBlock Element3 => _element3 ??= (ParagraphBlock)Document[3];
        private LinkInline? _element3_0;
        internal LinkInline Element3_0 => _element3_0 ??= (LinkInline)Element3.Inline!.FirstChild!;
        private LiteralInline? _element3_0_0;
        internal LiteralInline Element3_0_0 => _element3_0_0 ??= (LiteralInline)Element3_0.FirstChild!;
        private ParagraphBlock? _element4;
        internal ParagraphBlock Element4 => _element4 ??= (ParagraphBlock)Document[4];
        private LiteralInline? _element4_0;
        internal LiteralInline Element4_0 => _element4_0 ??= (LiteralInline)Element4.Inline!.FirstChild!;
        private HtmlEntityInline? _element4_1;
        internal HtmlEntityInline Element4_1 => _element4_1 ??= (HtmlEntityInline)Element4_0.NextSibling!;
        private LineBreakInline? _element4_2;
        internal LineBreakInline Element4_2 => _element4_2 ??= (LineBreakInline)Element4.Inline!.LastChild!;
        private HtmlAttributes? _element4_2_Attributes;
        internal HtmlAttributes Element4_2_Attributes => _element4_2_Attributes ??= Element4_2.GetAttributes();
        private ParagraphBlock? _element5;
        internal ParagraphBlock Element5 => _element5 ??= (ParagraphBlock)Document[5];
        private LiteralInline? _element5_0;
        internal LiteralInline Element5_0 => _element5_0 ??= (LiteralInline)Element5.Inline!.FirstChild!;
        private HtmlEntityInline? _element5_1;
        internal HtmlEntityInline Element5_1 => _element5_1 ??= (HtmlEntityInline)Element5_0.NextSibling!;
        private LiteralInline? _element5_2;
        internal LiteralInline Element5_2 => _element5_2 ??= (LiteralInline)Element5_1.NextSibling!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element5_3;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element5_3 => _element5_3 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element5_2.NextSibling!;
        private LiteralInline? _element5_4;
        internal LiteralInline Element5_4 => _element5_4 ??= (LiteralInline)Element5_5.PreviousSibling!;
        private LinkInline? _element5_5;
        internal LinkInline Element5_5 => _element5_5 ??= (LinkInline)Element5_6.PreviousSibling!;
        private LiteralInline? _element5_5_0;
        internal LiteralInline Element5_5_0 => _element5_5_0 ??= (LiteralInline)Element5_5.FirstChild!;
        private LiteralInline? _element5_6;
        internal LiteralInline Element5_6 => _element5_6 ??= (LiteralInline)Element5.Inline!.LastChild!;
        private HeadingBlock? _element6;
        internal HeadingBlock Element6 => _element6 ??= (HeadingBlock)Document[6];
        private HtmlAttributes? _element6_Attributes;
        internal HtmlAttributes Element6_Attributes => _element6_Attributes ?? Element6.GetAttributes();
        private LiteralInline? _element6_0;
        internal LiteralInline Element6_0 => _element6_0 ??= (LiteralInline)Element6.Inline!.FirstChild!;
        private HeadingBlock? _element7;
        internal HeadingBlock Element7 => _element7 ??= (HeadingBlock)Document[7];
        private HtmlAttributes? _element7_Attributes;
        internal HtmlAttributes Element7_Attributes => _element7_Attributes ?? Element7.GetAttributes();
        private LiteralInline? _element7_0;
        internal LiteralInline Element7_0 => _element7_0 ??= (LiteralInline)Element7.Inline!.FirstChild!;
        private ParagraphBlock? _element8;
        internal ParagraphBlock Element8 => _element8 ??= (ParagraphBlock)Document[8];
        private LinkInline? _element8_0;
        internal LinkInline Element8_0 => _element8_0 ??= (LinkInline)Element8.Inline!.FirstChild!;
        private LiteralInline? _element8_0_0;
        internal LiteralInline Element8_0_0 => _element8_0_0 ??= (LiteralInline)Element8_0.FirstChild!;
        private ParagraphBlock? _element9;
        internal ParagraphBlock Element9 => _element9 ??= (ParagraphBlock)Document[9];
        private LiteralInline? _element9_0;
        internal LiteralInline Element9_0 => _element9_0 ??= (LiteralInline)Element9.Inline!.FirstChild!;
        private LinkInline? _element9_1;
        internal LinkInline Element9_1 => _element9_1 ??= (LinkInline)Element9_0.NextSibling!;
        private LiteralInline? _element9_1_0;
        internal LiteralInline Element9_1_0 => _element9_1_0 ??= (LiteralInline)Element9_1.FirstChild!;
        private LiteralInline? _element9_2;
        internal LiteralInline Element9_2 => _element9_2 ??= (LiteralInline)Element9.Inline!.LastChild!;
        private ParagraphBlock? _element10;
        internal ParagraphBlock Element10 => _element10 ??= (ParagraphBlock)Document[10];
        private AutolinkInline? _element10_0;
        internal AutolinkInline Element10_0 => _element10_0 ??= (AutolinkInline)Element10.Inline!.FirstChild!;
        private LineBreakInline? _element10_1;
        internal LineBreakInline Element10_1 => _element10_1 ??= (LineBreakInline)Element10_0.NextSibling!;
        private AutolinkInline? _element10_2;
        internal AutolinkInline Element10_2 => _element10_2 ??= (AutolinkInline)Element10_1.NextSibling!;
        private LineBreakInline? _element10_3;
        internal LineBreakInline Element10_3 => _element10_3 ??= (LineBreakInline)Element10_4.PreviousSibling!;
        private LinkInline? _element10_4;
        internal LinkInline Element10_4 => _element10_4 ??= (LinkInline)Element10.Inline!.LastChild!;
        private LiteralInline? _element10_4_0;
        internal LiteralInline Element10_4_0 => _element10_4_0 ??= (LiteralInline)Element10_4.FirstChild!;
        private ParagraphBlock? _element11;
        internal ParagraphBlock Element11 => _element11 ??= (ParagraphBlock)Document[11];
        private LiteralInline? _element11_0;
        internal LiteralInline Element11_0 => _element11_0 ??= (LiteralInline)Element11.Inline!.FirstChild!;
        private LineBreakInline? _element11_1;
        internal LineBreakInline Element11_1 => _element11_1 ??= (LineBreakInline)Element11_0.NextSibling!;
        private LiteralInline? _element11_2;
        internal LiteralInline Element11_2 => _element11_2 ??= (LiteralInline)Element11.Inline!.LastChild!;
        private ParagraphBlock? _element12;
        internal ParagraphBlock Element12 => _element12 ??= (ParagraphBlock)Document[12];
        private LiteralInline? _element12_0;
        internal LiteralInline Element12_0 => _element12_0 ??= (LiteralInline)Element12.Inline!.FirstChild!;
        private LineBreakInline? _element12_1;
        internal LineBreakInline Element12_1 => _element12_1 ??= (LineBreakInline)Element12_0.NextSibling!;
        private LiteralInline? _element12_2;
        internal LiteralInline Element12_2 => _element12_2 ??= (LiteralInline)Element12.Inline!.LastChild!;
        private ListBlock? _element13;
        internal ListBlock Element13 => _element13 ??= (ListBlock)Document[13];
        private HtmlAttributes? _element13_Attributes;
        internal HtmlAttributes Element13_Attributes => _element13_Attributes ?? Element13.GetAttributes();
        private ListItemBlock? _element13_0;
        internal ListItemBlock Element13_0 => _element13_0 ??= (ListItemBlock)Element13[0]!;
        private HtmlAttributes? _element13_0_Attributes;
        internal HtmlAttributes Element13_0_Attributes => _element13_0_Attributes ?? Element13_0.GetAttributes();
        private ParagraphBlock? _element13_0_0;
        internal ParagraphBlock Element13_0_0 => _element13_0_0 ??= (ParagraphBlock)Element13_0[0]!;
        private Markdig.Extensions.TaskLists.TaskList? _element13_0_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element13_0_0_0 => _element13_0_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element13_0_0.Inline!.FirstChild!;
        private LiteralInline? _element13_0_0_1;
        internal LiteralInline Element13_0_0_1 => _element13_0_0_1 ??= (LiteralInline)Element13_0_0.Inline!.LastChild!;
        private ListItemBlock? _element13_1;
        internal ListItemBlock Element13_1 => _element13_1 ??= (ListItemBlock)Element13[1]!;
        private HtmlAttributes? _element13_1_Attributes;
        internal HtmlAttributes Element13_1_Attributes => _element13_1_Attributes ?? Element13_1.GetAttributes();
        private ParagraphBlock? _element13_1_0;
        internal ParagraphBlock Element13_1_0 => _element13_1_0 ??= (ParagraphBlock)Element13_1[0]!;
        private Markdig.Extensions.TaskLists.TaskList? _element13_1_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element13_1_0_0 => _element13_1_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element13_1_0.Inline!.FirstChild!;
        private LiteralInline? _element13_1_0_1;
        internal LiteralInline Element13_1_0_1 => _element13_1_0_1 ??= (LiteralInline)Element13_1_0.Inline!.LastChild!;
        private ListItemBlock? _element13_2;
        internal ListItemBlock Element13_2 => _element13_2 ??= (ListItemBlock)Element13[2]!;
        private ParagraphBlock? _element13_2_0;
        internal ParagraphBlock Element13_2_0 => _element13_2_0 ??= (ParagraphBlock)Element13_2[0]!;
        private LiteralInline? _element13_2_0_1;
        internal LiteralInline Element13_2_0_1 => _element13_2_0_1 ??= (LiteralInline)Element13_2_0.Inline!.FirstChild!;
        private ListItemBlock? _element13_3;
        internal ListItemBlock Element13_3 => _element13_3 ??= (ListItemBlock)Element13[3]!;
        private ParagraphBlock? _element13_3_0;
        internal ParagraphBlock Element13_3_0 => _element13_3_0 ??= (ParagraphBlock)Element13_3[0]!;
        private LiteralInline? _element13_3_0_0;
        internal LiteralInline Element13_3_0_0 => _element13_3_0_0 ??= (LiteralInline)Element13_3_0.Inline!.FirstChild!;
        private ListBlock? _element14;
        internal ListBlock Element14 => _element14 ??= (ListBlock)Document[14];
        private ListItemBlock? _element14_0;
        internal ListItemBlock Element14_0 => _element14_0 ??= (ListItemBlock)Element14[0]!;
        private ParagraphBlock? _element14_0_0;
        internal ParagraphBlock Element14_0_0 => _element14_0_0 ??= (ParagraphBlock)Element14_0[0]!;
        private LiteralInline? _element14_0_0_0;
        internal LiteralInline Element14_0_0_0 => _element14_0_0_0 ??= (LiteralInline)Element14_0_0.Inline!.FirstChild!;
        private ListItemBlock? _element14_1;
        internal ListItemBlock Element14_1 => _element14_1 ??= (ListItemBlock)Element14[1]!;
        private ParagraphBlock? _element14_1_0;
        internal ParagraphBlock Element14_1_0 => _element14_1_0 ??= (ParagraphBlock)Element14_1[0]!;
        private LiteralInline? _element14_1_0_0;
        internal LiteralInline Element14_1_0_0 => _element14_1_0_0 ??= (LiteralInline)Element14_1_0.Inline!.FirstChild!;
        private ParagraphBlock? _element15;
        internal ParagraphBlock Element15 => _element15 ??= (ParagraphBlock)Document[15];
        private LiteralInline? _element15_0;
        internal LiteralInline Element15_0 => _element15_0 ??= (LiteralInline)Element15.Inline!.FirstChild!;
        private Markdig.Extensions.Abbreviations.AbbreviationInline? _element15_1;
        internal Markdig.Extensions.Abbreviations.AbbreviationInline Element15_1 => _element15_1 ??= (Markdig.Extensions.Abbreviations.AbbreviationInline)Element15_0.NextSibling!;
        private LiteralInline? _element15_2;
        internal LiteralInline Element15_2 => _element15_2 ??= (LiteralInline)Element15_1.NextSibling!;
        private LiteralInline? _element15_3;
        internal LiteralInline Element15_3 => _element15_3 ??= (LiteralInline)Element15_2.NextSibling!;
        private LineBreakInline? _element15_4;
        internal LineBreakInline Element15_4 => _element15_4 ??= (LineBreakInline)Element15_3.NextSibling!;
        private LiteralInline? _element15_5;
        internal LiteralInline Element15_5 => _element15_5 ??= (LiteralInline)Element15_4.NextSibling!;
        private Markdig.Extensions.Abbreviations.AbbreviationInline? _element15_6;
        internal Markdig.Extensions.Abbreviations.AbbreviationInline Element15_6 => _element15_6 ??= (Markdig.Extensions.Abbreviations.AbbreviationInline)Element15_7.PreviousSibling!;
        private LiteralInline? _element15_7;
        internal LiteralInline Element15_7 => _element15_7 ??= (LiteralInline)Element15_8.PreviousSibling!;
        private Markdig.Extensions.Abbreviations.AbbreviationInline? _element15_8;
        internal Markdig.Extensions.Abbreviations.AbbreviationInline Element15_8 => _element15_8 ??= (Markdig.Extensions.Abbreviations.AbbreviationInline)Element15_9.PreviousSibling!;
        private LiteralInline? _element15_9;
        internal LiteralInline Element15_9 => _element15_9 ??= (LiteralInline)Element15_10.PreviousSibling!;
        private LiteralInline? _element15_10;
        internal LiteralInline Element15_10 => _element15_10 ??= (LiteralInline)Element15.Inline!.LastChild!;
        private QuoteBlock? _element16;
        internal QuoteBlock Element16 => _element16 ??= (QuoteBlock)Document[16];
        private ParagraphBlock? _element16_0;
        internal ParagraphBlock Element16_0 => _element16_0 ??= (ParagraphBlock)Element16[0];
        private LiteralInline? _element16_0_0;
        internal LiteralInline Element16_0_0 => _element16_0_0 ??= (LiteralInline)Element16_0.Inline!.FirstChild!;
        private LineBreakInline? _element16_0_1;
        internal LineBreakInline Element16_0_1 => _element16_0_1 ??= (LineBreakInline)Element16_0_0.NextSibling!;
        private EmphasisInline? _element16_0_2;
        internal EmphasisInline Element16_0_2 => _element16_0_2 ??= (EmphasisInline)Element16_0.Inline!.LastChild!;
        private LiteralInline? _element16_0_2_0;
        internal LiteralInline Element16_0_2_0 => _element16_0_2_0 ??= (LiteralInline)Element16_0_2.FirstChild!;
        private ParagraphBlock? _element16_1;
        internal ParagraphBlock Element16_1 => _element16_1 ??= (ParagraphBlock)Element16[1];
        private LiteralInline? _element16_1_0;
        internal LiteralInline Element16_1_0 => _element16_1_0 ??= (LiteralInline)Element16_1.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.Table? _element17;
        internal Markdig.Extensions.Tables.Table Element17 => _element17 ??= (Markdig.Extensions.Tables.Table)Document[17];
        private Markdig.Extensions.Tables.TableRow? _element17_0;
        internal Markdig.Extensions.Tables.TableRow Element17_0 => _element17_0 ??= (Markdig.Extensions.Tables.TableRow)Element17[0];
        private Markdig.Extensions.Tables.TableCell? _element17_0_0;
        internal Markdig.Extensions.Tables.TableCell Element17_0_0 => _element17_0_0 ??= (Markdig.Extensions.Tables.TableCell)Element17_0[0];
        private ParagraphBlock? _element17_0_0_0;
        internal ParagraphBlock Element17_0_0_0 => _element17_0_0_0 ??= (ParagraphBlock)Element17_0_0[0];
        private LiteralInline? _element17_0_0_0_0;
        internal LiteralInline Element17_0_0_0_0 => _element17_0_0_0_0 ??= (LiteralInline)Element17_0_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element17_0_1;
        internal Markdig.Extensions.Tables.TableCell Element17_0_1 => _element17_0_1 ??= (Markdig.Extensions.Tables.TableCell)Element17_0[1];
        private ParagraphBlock? _element17_0_1_0;
        internal ParagraphBlock Element17_0_1_0 => _element17_0_1_0 ??= (ParagraphBlock)Element17_0_1[0];
        private LiteralInline? _element17_0_1_0_0;
        internal LiteralInline Element17_0_1_0_0 => _element17_0_1_0_0 ??= (LiteralInline)Element17_0_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableRow? _element17_1;
        internal Markdig.Extensions.Tables.TableRow Element17_1 => _element17_1 ??= (Markdig.Extensions.Tables.TableRow)Element17[1];
        private Markdig.Extensions.Tables.TableCell? _element17_1_0;
        internal Markdig.Extensions.Tables.TableCell Element17_1_0 => _element17_1_0 ??= (Markdig.Extensions.Tables.TableCell)Element17_1[0];
        private ParagraphBlock? _element17_1_0_0;
        internal ParagraphBlock Element17_1_0_0 => _element17_1_0_0 ??= (ParagraphBlock)Element17_1_0[0];
        private LiteralInline? _element17_1_0_0_0;
        internal LiteralInline Element17_1_0_0_0 => _element17_1_0_0_0 ??= (LiteralInline)Element17_1_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element17_1_1;
        internal Markdig.Extensions.Tables.TableCell Element17_1_1 => _element17_1_1 ??= (Markdig.Extensions.Tables.TableCell)Element17_1[1];
        private ParagraphBlock? _element17_1_1_0;
        internal ParagraphBlock Element17_1_1_0 => _element17_1_1_0 ??= (ParagraphBlock)Element17_1_1[0];
        private LiteralInline? _element17_1_1_0_0;
        internal LiteralInline Element17_1_1_0_0 => _element17_1_1_0_0 ??= (LiteralInline)Element17_1_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableRow? _element17_2;
        internal Markdig.Extensions.Tables.TableRow Element17_2 => _element17_2 ??= (Markdig.Extensions.Tables.TableRow)Element17[2];
        private Markdig.Extensions.Tables.TableCell? _element17_2_0;
        internal Markdig.Extensions.Tables.TableCell Element17_2_0 => _element17_2_0 ??= (Markdig.Extensions.Tables.TableCell)Element17_2[0];
        private ParagraphBlock? _element17_2_0_0;
        internal ParagraphBlock Element17_2_0_0 => _element17_2_0_0 ??= (ParagraphBlock)Element17_2_0[0];
        private LiteralInline? _element17_2_0_0_0;
        internal LiteralInline Element17_2_0_0_0 => _element17_2_0_0_0 ??= (LiteralInline)Element17_2_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element17_2_1;
        internal Markdig.Extensions.Tables.TableCell Element17_2_1 => _element17_2_1 ??= (Markdig.Extensions.Tables.TableCell)Element17_2[1];
        private ParagraphBlock? _element17_2_1_0;
        internal ParagraphBlock Element17_2_1_0 => _element17_2_1_0 ??= (ParagraphBlock)Element17_2_1[0];
        private LiteralInline? _element17_2_1_0_0;
        internal LiteralInline Element17_2_1_0_0 => _element17_2_1_0_0 ??= (LiteralInline)Element17_2_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.Table? _element18;
        internal Markdig.Extensions.Tables.Table Element18 => _element18 ??= (Markdig.Extensions.Tables.Table)Document[18];
        private Markdig.Extensions.Tables.TableRow? _element18_0;
        internal Markdig.Extensions.Tables.TableRow Element18_0 => _element18_0 ??= (Markdig.Extensions.Tables.TableRow)Element18[0];
        private Markdig.Extensions.Tables.TableCell? _element18_0_0;
        internal Markdig.Extensions.Tables.TableCell Element18_0_0 => _element18_0_0 ??= (Markdig.Extensions.Tables.TableCell)Element18_0[0];
        private ParagraphBlock? _element18_0_0_0;
        internal ParagraphBlock Element18_0_0_0 => _element18_0_0_0 ??= (ParagraphBlock)Element18_0_0[0];
        private LiteralInline? _element18_0_0_0_0;
        internal LiteralInline Element18_0_0_0_0 => _element18_0_0_0_0 ??= (LiteralInline)Element18_0_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_0_1;
        internal Markdig.Extensions.Tables.TableCell Element18_0_1 => _element18_0_1 ??= (Markdig.Extensions.Tables.TableCell)Element18_0[1];
        private ParagraphBlock? _element18_0_1_0;
        internal ParagraphBlock Element18_0_1_0 => _element18_0_1_0 ??= (ParagraphBlock)Element18_0_1[0];
        private LiteralInline? _element18_0_1_0_0;
        internal LiteralInline Element18_0_1_0_0 => _element18_0_1_0_0 ??= (LiteralInline)Element18_0_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_0_2;
        internal Markdig.Extensions.Tables.TableCell Element18_0_2 => _element18_0_2 ??= (Markdig.Extensions.Tables.TableCell)Element18_0[2];
        private ParagraphBlock? _element18_0_2_0;
        internal ParagraphBlock Element18_0_2_0 => _element18_0_2_0 ??= (ParagraphBlock)Element18_0_2[0];
        private LiteralInline? _element18_0_2_0_0;
        internal LiteralInline Element18_0_2_0_0 => _element18_0_2_0_0 ??= (LiteralInline)Element18_0_2_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableRow? _element18_1;
        internal Markdig.Extensions.Tables.TableRow Element18_1 => _element18_1 ??= (Markdig.Extensions.Tables.TableRow)Element18[1];
        private Markdig.Extensions.Tables.TableCell? _element18_1_0;
        internal Markdig.Extensions.Tables.TableCell Element18_1_0 => _element18_1_0 ??= (Markdig.Extensions.Tables.TableCell)Element18_1[0];
        private ParagraphBlock? _element18_1_0_0;
        internal ParagraphBlock Element18_1_0_0 => _element18_1_0_0 ??= (ParagraphBlock)Element18_1_0[0];
        private LiteralInline? _element18_1_0_0_0;
        internal LiteralInline Element18_1_0_0_0 => _element18_1_0_0_0 ??= (LiteralInline)Element18_1_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_1_1;
        internal Markdig.Extensions.Tables.TableCell Element18_1_1 => _element18_1_1 ??= (Markdig.Extensions.Tables.TableCell)Element18_1[1];
        private ParagraphBlock? _element18_1_1_0;
        internal ParagraphBlock Element18_1_1_0 => _element18_1_1_0 ??= (ParagraphBlock)Element18_1_1[0];
        private LiteralInline? _element18_1_1_0_0;
        internal LiteralInline Element18_1_1_0_0 => _element18_1_1_0_0 ??= (LiteralInline)Element18_1_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_1_2;
        internal Markdig.Extensions.Tables.TableCell Element18_1_2 => _element18_1_2 ??= (Markdig.Extensions.Tables.TableCell)Element18_1[2];
        private ParagraphBlock? _element18_1_2_0;
        internal ParagraphBlock Element18_1_2_0 => _element18_1_2_0 ??= (ParagraphBlock)Element18_1_2[0];
        private LiteralInline? _element18_1_2_0_0;
        internal LiteralInline Element18_1_2_0_0 => _element18_1_2_0_0 ??= (LiteralInline)Element18_1_2_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableRow? _element18_2;
        internal Markdig.Extensions.Tables.TableRow Element18_2 => _element18_2 ??= (Markdig.Extensions.Tables.TableRow)Element18[2];
        private Markdig.Extensions.Tables.TableCell? _element18_2_0;
        internal Markdig.Extensions.Tables.TableCell Element18_2_0 => _element18_2_0 ??= (Markdig.Extensions.Tables.TableCell)Element18_2[0];
        private ParagraphBlock? _element18_2_0_0;
        internal ParagraphBlock Element18_2_0_0 => _element18_2_0_0 ??= (ParagraphBlock)Element18_2_0[0];
        private LiteralInline? _element18_2_0_0_0;
        internal LiteralInline Element18_2_0_0_0 => _element18_2_0_0_0 ??= (LiteralInline)Element18_2_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_2_1;
        internal Markdig.Extensions.Tables.TableCell Element18_2_1 => _element18_2_1 ??= (Markdig.Extensions.Tables.TableCell)Element18_2[1];
        private ParagraphBlock? _element18_2_1_0;
        internal ParagraphBlock Element18_2_1_0 => _element18_2_1_0 ??= (ParagraphBlock)Element18_2_1[0];
        private LiteralInline? _element18_2_1_0_0;
        internal LiteralInline Element18_2_1_0_0 => _element18_2_1_0_0 ??= (LiteralInline)Element18_2_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Tables.TableCell? _element18_2_2;
        internal Markdig.Extensions.Tables.TableCell Element18_2_2 => _element18_2_2 ??= (Markdig.Extensions.Tables.TableCell)Element18_2[2];
        private ParagraphBlock? _element18_2_2_0;
        internal ParagraphBlock Element18_2_2_0 => _element18_2_2_0 ??= (ParagraphBlock)Element18_2_2[0];
        private LiteralInline? _element18_2_2_0_0;
        internal LiteralInline Element18_2_2_0_0 => _element18_2_2_0_0 ??= (LiteralInline)Element18_2_2_0.Inline!.FirstChild!;
        private HeadingBlock? _element19;
        internal HeadingBlock Element19 => _element19 ??= (HeadingBlock)Document[19];
        private HtmlAttributes? _element19_Attributes;
        internal HtmlAttributes Element19_Attributes => _element19_Attributes ?? Element19.GetAttributes();
        private LiteralInline? _element19_0;
        internal LiteralInline Element19_0 => _element19_0 ??= (LiteralInline)Element19.Inline!.FirstChild!;
        private ParagraphBlock? _element20;
        internal ParagraphBlock Element20 => _element20 ??= (ParagraphBlock)Document[20];
        private LinkInline? _element20_0;
        internal LinkInline Element20_0 => _element20_0 ??= (LinkInline)Element20.Inline!.FirstChild!;
        private LiteralInline? _element20_0_0;
        internal LiteralInline Element20_0_0 => _element20_0_0 ??= (LiteralInline)Element20_0.FirstChild!;
        private ParagraphBlock? _element21;
        internal ParagraphBlock Element21 => _element21 ??= (ParagraphBlock)Document[21];
        private LiteralInline? _element21_0;
        internal LiteralInline Element21_0 => _element21_0 ??= (LiteralInline)Element21.Inline!.FirstChild!;
        private EmphasisInline? _element21_1;
        internal EmphasisInline Element21_1 => _element21_1 ??= (EmphasisInline)Element21_0.NextSibling!;
        private LiteralInline? _element21_1_0;
        internal LiteralInline Element21_1_0 => _element21_1_0 ??= (LiteralInline)Element21_1.FirstChild!;
        private LiteralInline? _element21_2;
        internal LiteralInline Element21_2 => _element21_2 ??= (LiteralInline)Element21_1.NextSibling!;
        private EmphasisInline? _element21_3;
        internal EmphasisInline Element21_3 => _element21_3 ??= (EmphasisInline)Element21_4.PreviousSibling!;
        private LiteralInline? _element21_3_0;
        internal LiteralInline Element21_3_0 => _element21_3_0 ??= (LiteralInline)Element21_3.FirstChild!;
        private LiteralInline? _element21_4;
        internal LiteralInline Element21_4 => _element21_4 ??= (LiteralInline)Element21_5.PreviousSibling!;
        private Markdig.Extensions.Mathematics.MathInline? _element21_5;
        internal Markdig.Extensions.Mathematics.MathInline Element21_5 => _element21_5 ??= (Markdig.Extensions.Mathematics.MathInline)Element21.Inline!.LastChild!;
        private HtmlAttributes? _element21_5_Attributes;
        internal HtmlAttributes Element21_5_Attributes => _element21_5_Attributes ?? Element21_5.GetAttributes();
        private ParagraphBlock? _element22;
        internal ParagraphBlock Element22 => _element22 ??= (ParagraphBlock)Document[22];
        private LiteralInline? _element22_0;
        internal LiteralInline Element22_0 => _element22_0 ??= (LiteralInline)Element22.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element22_1;
        internal Markdig.Extensions.Mathematics.MathInline Element22_1 => _element22_1 ??= (Markdig.Extensions.Mathematics.MathInline)Element22.Inline!.LastChild!;
        private HtmlAttributes? _element22_1_Attributes;
        internal HtmlAttributes Element22_1_Attributes => _element22_1_Attributes ?? Element22_1.GetAttributes();
        private LiteralInline? _element22_2;
        internal LiteralInline Element22_2 => _element22_2 ??= (LiteralInline)Element22_1.NextSibling!;
        private Markdig.Extensions.Mathematics.MathInline? _element22_3;
        internal Markdig.Extensions.Mathematics.MathInline Element22_3 => _element22_3 ??= (Markdig.Extensions.Mathematics.MathInline)Element22_4.PreviousSibling!;
        private HtmlAttributes? _element22_3_Attributes;
        internal HtmlAttributes Element22_3_Attributes => _element22_3_Attributes ?? Element22_3.GetAttributes();
        private LiteralInline? _element22_4;
        internal LiteralInline Element22_4 => _element22_4 ??= (LiteralInline)Element22.Inline!.LastChild!;
        private ParagraphBlock? _element23;
        internal ParagraphBlock Element23 => _element23 ??= (ParagraphBlock)Document[23];
        private EmphasisInline? _element23_0;
        internal EmphasisInline Element23_0 => _element23_0 ??= (EmphasisInline)Element23.Inline!.FirstChild!;
        private LiteralInline? _element23_0_0;
        internal LiteralInline Element23_0_0 => _element23_0_0 ??= (LiteralInline)Element23_0.FirstChild!;
        private LineBreakInline? _element23_1;
        internal LineBreakInline Element23_1 => _element23_1 ??= (LineBreakInline)Element23_0.NextSibling!;
        private Markdig.Extensions.Mathematics.MathInline? _element23_2;
        internal Markdig.Extensions.Mathematics.MathInline Element23_2 => _element23_2 ??= (Markdig.Extensions.Mathematics.MathInline)Element23.Inline!.LastChild!;
        private HtmlAttributes? _element23_2_Attributes;
        internal HtmlAttributes Element23_2_Attributes => _element23_2_Attributes ?? Element23_2.GetAttributes();
        private ParagraphBlock? _element24;
        internal ParagraphBlock Element24 => _element24 ??= (ParagraphBlock)Document[24];
        private LiteralInline? _element24_0;
        internal LiteralInline Element24_0 => _element24_0 ??= (LiteralInline)Element24.Inline!.FirstChild!;
        private CodeInline? _element24_1;
        internal CodeInline Element24_1 => _element24_1 ??= (CodeInline)Element24_0.NextSibling!;
        private LiteralInline? _element24_2;
        internal LiteralInline Element24_2 => _element24_2 ??= (LiteralInline)Element24.Inline!.LastChild!;
        private ThematicBreakBlock? _element25;
        internal ThematicBreakBlock Element25 => _element25 ??= (ThematicBreakBlock)Document[25];
        private ParagraphBlock? _element26;
        internal ParagraphBlock Element26 => _element26 ??= (ParagraphBlock)Document[26];
        private EmphasisInline? _element26_0;
        internal EmphasisInline Element26_0 => _element26_0 ??= (EmphasisInline)Element26.Inline!.FirstChild!;
        private LiteralInline? _element26_0_0;
        internal LiteralInline Element26_0_0 => _element26_0_0 ??= (LiteralInline)Element26_0.FirstChild!;
        private LiteralInline? _element26_1;
        internal LiteralInline Element26_1 => _element26_1 ??= (LiteralInline)Element26_0.NextSibling!;
        private EmphasisInline? _element26_2;
        internal EmphasisInline Element26_2 => _element26_2 ??= (EmphasisInline)Element26_3.PreviousSibling!;
        private LiteralInline? _element26_2_0;
        internal LiteralInline Element26_2_0 => _element26_2_0 ??= (LiteralInline)Element26_2.FirstChild!;
        private LiteralInline? _element26_3;
        internal LiteralInline Element26_3 => _element26_3 ??= (LiteralInline)Element26.Inline!.LastChild!;
        private FencedCodeBlock? _element27;
        internal FencedCodeBlock Element27 => _element27 ??= (FencedCodeBlock)Document[27];
        private HtmlAttributes? _element27_Attributes;
        internal HtmlAttributes Element27_Attributes => _element27_Attributes ?? Element27.GetAttributes();
        private FencedCodeBlock? _element28;
        internal FencedCodeBlock Element28 => _element28 ??= (FencedCodeBlock)Document[28];
        private HtmlAttributes? _element28_Attributes;
        internal HtmlAttributes Element28_Attributes => _element28_Attributes ?? Element28.GetAttributes();
        private Markdig.Extensions.DefinitionLists.DefinitionList? _element29;
        internal Markdig.Extensions.DefinitionLists.DefinitionList Element29 => _element29 ??= (Markdig.Extensions.DefinitionLists.DefinitionList)Document[29];
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element29_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element29_0 => _element29_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element29[0];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element29_0_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element29_0_0 => _element29_0_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element29_0[0];
        private LiteralInline? _element29_0_0_0;
        internal LiteralInline Element29_0_0_0 => _element29_0_0_0 ??= (LiteralInline)Element29_0_0.Inline!.FirstChild!;
        private ParagraphBlock? _element29_0_1;
        internal ParagraphBlock Element29_0_1 => _element29_0_1 ??= (ParagraphBlock)Element29_0[1];
        private LiteralInline? _element29_0_1_0;
        internal LiteralInline Element29_0_1_0 => _element29_0_1_0 ??= (LiteralInline)Element29_0_1.Inline!.FirstChild!;
        private LiteralInline? _element29_0_1_1;
        internal LiteralInline Element29_0_1_1 => _element29_0_1_1 ??= (LiteralInline)Element29_0_1_0.NextSibling!;
        private LiteralInline? _element29_0_1_2;
        internal LiteralInline Element29_0_1_2 => _element29_0_1_2 ??= (LiteralInline)Element29_0_1.Inline!.LastChild!;
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element29_1;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element29_1 => _element29_1 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element29[1];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element29_1_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element29_1_0 => _element29_1_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element29_1[0];
        private LiteralInline? _element29_1_0_0;
        internal LiteralInline Element29_1_0_0 => _element29_1_0_0 ??= (LiteralInline)Element29_1_0.Inline!.FirstChild!;
        private ParagraphBlock? _element29_1_1;
        internal ParagraphBlock Element29_1_1 => _element29_1_1 ??= (ParagraphBlock)Element29_1[1];
        private LiteralInline? _element29_1_1_0;
        internal LiteralInline Element29_1_1_0 => _element29_1_1_0 ??= (LiteralInline)Element29_1_1.Inline!.FirstChild!;
        private LinkReferenceDefinitionGroup? _element30;
        internal LinkReferenceDefinitionGroup Element30 => _element30 ??= (LinkReferenceDefinitionGroup)Document[30];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element30_0;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element30_0 => _element30_0 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element30[0];
        private LinkReferenceDefinition? _element30_1;
        internal LinkReferenceDefinition Element30_1 => _element30_1 ??= (LinkReferenceDefinition)Element30[2];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element30_2;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element30_2 => _element30_2 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element30[2];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element30_3;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element30_3 => _element30_3 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element30[3];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element30_4;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element30_4 => _element30_4 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element30[4];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element30_5;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element30_5 => _element30_5 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element30[5];
        private Markdig.Extensions.Footnotes.FootnoteGroup? _element31;
        internal Markdig.Extensions.Footnotes.FootnoteGroup Element31 => _element31 ??= (Markdig.Extensions.Footnotes.FootnoteGroup)Document[31];
        private Markdig.Extensions.Footnotes.Footnote? _element31_0;
        internal Markdig.Extensions.Footnotes.Footnote Element31_0 => _element31_0 ??= (Markdig.Extensions.Footnotes.Footnote)Element31[0];
        private ParagraphBlock? _element31_0_0;
        internal ParagraphBlock Element31_0_0 => _element31_0_0 ??= (ParagraphBlock)Element31_0[0];
        private LiteralInline? _element31_0_0_0;
        internal LiteralInline Element31_0_0_0 => _element31_0_0_0 ??= (LiteralInline)Element31_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element31_0_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element31_0_0_1 => _element31_0_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element31_0_0.Inline!.LastChild!;
        private Markdig.Extensions.Footnotes.Footnote? _element31_1;
        internal Markdig.Extensions.Footnotes.Footnote Element31_1 => _element31_1 ??= (Markdig.Extensions.Footnotes.Footnote)Element31[1];
        private ParagraphBlock? _element31_1_0;
        internal ParagraphBlock Element31_1_0 => _element31_1_0 ??= (ParagraphBlock)Element31_1[0];
        private LiteralInline? _element31_1_0_0;
        internal LiteralInline Element31_1_0_0 => _element31_1_0_0 ??= (LiteralInline)Element31_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element31_1_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element31_1_0_1 => _element31_1_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element31_1_0.Inline!.LastChild!;

        internal MarkdownElements(MarkdownDocument markdownDocument)
        {
            Document = markdownDocument;
        }
    }
    
    [Obsolete("Use ExampleMarkdown1.MarkdownElements")]
    class MarkdownElementsOld
    {
        internal MarkdownDocument Document { get; init; }

        private HeadingBlock? _element0;
        internal HeadingBlock Element0 => _element0 ??= (HeadingBlock)Document[0];
        private HtmlAttributes? _element0_Attributes;
        internal HtmlAttributes Element0_Attributes => _element0_Attributes ?? Element0.GetAttributes();
        private LiteralInline? _element0_0;
        internal LiteralInline Element0_0 => _element0_0 ??= (LiteralInline)Element0.Inline!.FirstChild!;
        private ParagraphBlock? _element1;
        internal ParagraphBlock Element1 => _element1 ??= (ParagraphBlock)Document[1];
        private LinkInline? _element1_0;
        internal LinkInline Element1_0 => _element1_0 ??= (LinkInline)Element1.Inline!.FirstChild!;
        private LiteralInline? _element1_0_0;
        internal LiteralInline Element1_0_0 => _element1_0_0 ??= (LiteralInline)Element1_0.FirstChild!;
        private ParagraphBlock? _element2;
        internal ParagraphBlock Element2 => _element2 ??= (ParagraphBlock)Document[2];
        private LiteralInline? _element2_0;
        internal LiteralInline Element2_0 => _element2_0 ??= (LiteralInline)Element2.Inline!.FirstChild!;
        private LineBreakInline? _element2_1;
        internal LineBreakInline Element2_1 => _element2_1 ??= (LineBreakInline)Element2_0.NextSibling!;
        private LiteralInline? _element2_2;
        internal LiteralInline Element2_2 => _element2_2 ??= (LiteralInline)Element2.Inline!.LastChild!;
        private ListBlock? _element3;
        internal ListBlock Element3 => _element3 ??= (ListBlock)Document[3];
        private HtmlAttributes? _element3_Attributes;
        internal HtmlAttributes Element3_Attributes => _element3_Attributes ?? Element3.GetAttributes();
        private ListItemBlock? _element3_0;
        internal ListItemBlock Element3_0 => _element3_0 ??= (ListItemBlock)Element3[0];
        private HtmlAttributes? _element3_0_Attributes;
        internal HtmlAttributes Element3_0_Attributes => _element3_0_Attributes ?? Element3_0.GetAttributes();
        private ParagraphBlock? _element3_0_0;
        internal ParagraphBlock Element3_0_0 => _element3_0_0 ??= (ParagraphBlock)Element3_0[0];
        private Markdig.Extensions.TaskLists.TaskList? _element3_0_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element3_0_0_0 => _element3_0_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element3_0_0.Inline!.FirstChild!;
        private LiteralInline? _element3_0_0_1;
        internal LiteralInline Element3_0_0_1 => _element3_0_0_1 ??= (LiteralInline)Element3_0_0.Inline!.LastChild!;
        private ListItemBlock? _element3_1;
        internal ListItemBlock Element3_1 => _element3_1 ??= (ListItemBlock)Element3[1];
        private HtmlAttributes? _element3_1_Attributes;
        internal HtmlAttributes Element3_1_Attributes => _element3_1_Attributes ?? Element3_1.GetAttributes();
        private ParagraphBlock? _element3_1_0;
        internal ParagraphBlock Element3_1_0 => _element3_1_0 ??= (ParagraphBlock)Element3_1[0];
        private Markdig.Extensions.TaskLists.TaskList? _element3_1_0_0;
        internal Markdig.Extensions.TaskLists.TaskList Element3_1_0_0 => _element3_1_0_0 ??= (Markdig.Extensions.TaskLists.TaskList)Element3_1_0.Inline!.FirstChild!;
        private LiteralInline? _element3_1_0_1;
        internal LiteralInline Element3_1_0_1 => _element3_1_0_1 ??= (LiteralInline)Element3_1_0.Inline!.LastChild!;
        private ListItemBlock? _element3_2;
        internal ListItemBlock Element3_2 => _element3_2 ??= (ListItemBlock)Element3[2];
        private ParagraphBlock? _element3_2_0;
        internal ParagraphBlock Element3_2_0 => _element3_2_0 ??= (ParagraphBlock)Element3_2[0];
        private LiteralInline? _element3_2_0_0;
        internal LiteralInline Element3_2_0_0 => _element3_2_0_0 ??= (LiteralInline)Element3_2_0.Inline!.FirstChild!;
        private ListItemBlock? _element3_3;
        internal ListItemBlock Element3_3 => _element3_3 ??= (ListItemBlock)Element3[3];
        private ParagraphBlock? _element3_3_0;
        internal ParagraphBlock Element3_3_0 => _element3_3_0 ??= (ParagraphBlock)Element3_3[0];
        private LiteralInline? _element3_3_0_0;
        internal LiteralInline Element3_3_0_0 => _element3_3_0_0 ??= (LiteralInline)Element3_3_0.Inline!.FirstChild!;
        private HeadingBlock? _element4;
        internal HeadingBlock Element4 => _element4 ??= (HeadingBlock)Document[4];
        private HtmlAttributes? _element4_Attributes;
        internal HtmlAttributes Element4_Attributes => _element4_Attributes ?? Element4.GetAttributes();
        private LiteralInline? _element4_0;
        internal LiteralInline Element4_0 => _element4_0 ??= (LiteralInline)Element4.Inline!.FirstChild!;
        private HeadingBlock? _element5;
        internal HeadingBlock Element5 => _element5 ??= (HeadingBlock)Document[5];
        private HtmlAttributes? _element5_Attributes;
        internal HtmlAttributes Element5_Attributes => _element5_Attributes ?? Element5.GetAttributes();
        private LiteralInline? _element5_0;
        internal LiteralInline Element5_0 => _element5_0 ??= (LiteralInline)Element5.Inline!.FirstChild!;
        private ParagraphBlock? _element6;
        internal ParagraphBlock Element6 => _element6 ??= (ParagraphBlock)Document[6];
        private LinkInline? _element6_0;
        internal LinkInline Element6_0 => _element6_0 ??= (LinkInline)Element6.Inline!.FirstChild!;
        private LiteralInline? _element6_0_0;
        internal LiteralInline Element6_0_0 => _element6_0_0 ??= (LiteralInline)Element6_0.FirstChild!;
        private HeadingBlock? _element7;
        internal HeadingBlock Element7 => _element7 ??= (HeadingBlock)Document[7];
        private HtmlAttributes? _element7_Attributes;
        internal HtmlAttributes Element7_Attributes => _element7_Attributes ?? Element7.GetAttributes();
        private LiteralInline? _element7_0;
        internal LiteralInline Element7_0 => _element7_0 ??= (LiteralInline)Element7.Inline!.FirstChild!;
        private ParagraphBlock? _element8;
        internal ParagraphBlock Element8 => _element8 ??= (ParagraphBlock)Document[8];
        private LinkInline? _element8_0;
        internal LinkInline Element8_0 => _element8_0 ??= (LinkInline)Element8.Inline!.FirstChild!;
        private LiteralInline? _element8_0_0;
        internal LiteralInline Element8_0_0 => _element8_0_0 ??= (LiteralInline)Element8_0.FirstChild!;
        private ParagraphBlock? _element9;
        internal ParagraphBlock Element9 => _element9 ??= (ParagraphBlock)Document[9];
        private LinkInline? _element9_0;
        internal LinkInline Element9_0 => _element9_0 ??= (LinkInline)Element9.Inline!.FirstChild!;
        private LiteralInline? _element9_0_0;
        internal LiteralInline Element9_0_0 => _element9_0_0 ??= (LiteralInline)Element9_0.FirstChild!;
        private EmphasisInline? _element9_0_1;
        internal EmphasisInline Element9_0_1 => _element9_0_1 ??= (EmphasisInline)Element9_0.LastChild!;
        private LiteralInline? _element9_0_1_0;
        internal LiteralInline Element9_0_1_0 => _element9_0_1_0 ??= (LiteralInline)Element9_0_1.FirstChild!;
        private LinkReferenceDefinitionGroup? _element10;
        internal LinkReferenceDefinitionGroup Element10 => _element10 ??= (LinkReferenceDefinitionGroup)Document[10];
        private LinkReferenceDefinition? _element10_0;
        internal LinkReferenceDefinition Element10_0 => _element10_0 ??= (LinkReferenceDefinition)Element10[0];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element10_1;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element10_1 => _element10_1 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element10[1];
        private Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition? _element10_2;
        internal Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition Element10_2 => _element10_2 ??= (Markdig.Extensions.Footnotes.FootnoteLinkReferenceDefinition)Element10[2];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_3;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_3 => _element10_3 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[3];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_4;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_4 => _element10_4 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[4];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_5;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_5 => _element10_5 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[5];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_6;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_6 => _element10_6 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[6];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_7;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_7 => _element10_7 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[7];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_8;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_8 => _element10_8 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[8];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_9;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_9 => _element10_9 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[9];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_10;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_10 => _element10_10 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[10];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_11;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_11 => _element10_11 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[11];
        private Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition? _element10_12;
        internal Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition Element10_12 => _element10_12 ??= (Markdig.Extensions.AutoIdentifiers.HeadingLinkReferenceDefinition)Element10[12];
        private HeadingBlock? _element11;
        internal HeadingBlock Element11 => _element11 ??= (HeadingBlock)Document[11];
        private HtmlAttributes? _element11_Attributes;
        internal HtmlAttributes Element11_Attributes => _element11_Attributes ?? Element11.GetAttributes();
        private LiteralInline? _element11_0;
        internal LiteralInline Element11_0 => _element11_0 ??= (LiteralInline)Element11.Inline!.FirstChild!;
        private ParagraphBlock? _element12;
        internal ParagraphBlock Element12 => _element12 ??= (ParagraphBlock)Document[12];
        private LiteralInline? _element12_0;
        internal LiteralInline Element12_0 => _element12_0 ??= (LiteralInline)Element12.Inline!.FirstChild!;
        private CodeInline? _element12_1;
        internal CodeInline Element12_1 => _element12_1 ??= (CodeInline)Element12_0.NextSibling!;
        private LiteralInline? _element12_2;
        internal LiteralInline Element12_2 => _element12_2 ??= (LiteralInline)Element12_1.NextSibling!;
        private Markdig.Extensions.Mathematics.MathInline? _element12_3;
        internal Markdig.Extensions.Mathematics.MathInline Element12_3 => _element12_3 ??= (Markdig.Extensions.Mathematics.MathInline)Element12.Inline!.LastChild!;
        private HtmlAttributes? _element12_3_Attributes;
        internal HtmlAttributes Element12_3_Attributes => _element12_3_Attributes ?? Element12_3.GetAttributes();
        private ParagraphBlock? _element13;
        internal ParagraphBlock Element13 => _element13 ??= (ParagraphBlock)Document[13];
        private LiteralInline? _element13_0;
        internal LiteralInline Element13_0 => _element13_0 ??= (LiteralInline)Element13.Inline!.FirstChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element13_1;
        internal Markdig.Extensions.Mathematics.MathInline Element13_1 => _element13_1 ??= (Markdig.Extensions.Mathematics.MathInline)Element13_0.NextSibling!;
        private HtmlAttributes? _element13_1_Attributes;
        internal HtmlAttributes Element13_1_Attributes => _element13_1_Attributes ?? Element13_1.GetAttributes();
        private LiteralInline? _element13_2;
        internal LiteralInline Element13_2 => _element13_2 ??= (LiteralInline)Element13.Inline!.LastChild!;
        private Markdig.Extensions.Mathematics.MathInline? _element13_3;
        internal Markdig.Extensions.Mathematics.MathInline Element13_3 => _element13_3 ??= (Markdig.Extensions.Mathematics.MathInline)Element13.Inline!.FirstChild!;
        private HtmlAttributes? _element13_3_Attributes;
        internal HtmlAttributes Element13_3_Attributes => _element13_3_Attributes ?? Element13_3.GetAttributes();
        private ParagraphBlock? _element14;
        internal ParagraphBlock Element14 => _element14 ??= (ParagraphBlock)Document[14];
        private EmphasisInline? _element14_0;
        internal EmphasisInline Element14_0 => _element14_0 ??= (EmphasisInline)Element14.Inline!.FirstChild!;
        private LiteralInline? _element14_0_0;
        internal LiteralInline Element14_0_0 => _element14_0_0 ??= (LiteralInline)Element14_0.FirstChild!;
        private LineBreakInline? _element14_1;
        internal LineBreakInline Element14_1 => _element14_1 ??= (LineBreakInline)Element14_0.NextSibling!;
        private Markdig.Extensions.Mathematics.MathInline? _element14_2;
        internal Markdig.Extensions.Mathematics.MathInline Element14_2 => _element14_2 ??= (Markdig.Extensions.Mathematics.MathInline)Element14.Inline!.LastChild!;
        private HtmlAttributes? _element14_2_Attributes;
        internal HtmlAttributes Element14_2_Attributes => _element14_2_Attributes ?? Element14_2.GetAttributes();
        private HeadingBlock? _element15;
        internal HeadingBlock Element15 => _element15 ??= (HeadingBlock)Document[15];
        private HtmlAttributes? _element15_Attributes;
        internal HtmlAttributes Element15_Attributes => _element15_Attributes ?? Element15.GetAttributes();
        private LiteralInline? _element15_0;
        internal LiteralInline Element15_0 => _element15_0 ??= (LiteralInline)Element15.Inline!.FirstChild!;
        private Markdig.Extensions.DefinitionLists.DefinitionList? _element16;
        internal Markdig.Extensions.DefinitionLists.DefinitionList Element16 => _element16 ??= (Markdig.Extensions.DefinitionLists.DefinitionList)Document[16];
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element16_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element16_0 => _element16_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element16[0];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element16_0_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element16_0_0 => _element16_0_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element16_0[0];
        private LiteralInline? _element16_0_0_0;
        internal LiteralInline Element16_0_0_0 => _element16_0_0_0 ??= (LiteralInline)Element16_0_0.Inline!.FirstChild!;
        private ParagraphBlock? _element16_0_1;
        internal ParagraphBlock Element16_0_1 => _element16_0_1 ??= (ParagraphBlock)Element16_0[1];
        private LiteralInline? _element16_0_1_0;
        internal LiteralInline Element16_0_1_0 => _element16_0_1_0 ??= (LiteralInline)Element16_0_1.Inline!.FirstChild!;
        private LineBreakInline? _element16_0_1_1;
        internal LineBreakInline Element16_0_1_1 => _element16_0_1_1 ??= (LineBreakInline)Element16_0_1_0.NextSibling!;
        private LiteralInline? _element16_0_1_2;
        internal LiteralInline Element16_0_1_2 => _element16_0_1_2 ??= (LiteralInline)Element16_0_1.Inline!.LastChild!;
        private Markdig.Extensions.DefinitionLists.DefinitionItem? _element16_1;
        internal Markdig.Extensions.DefinitionLists.DefinitionItem Element16_1 => _element16_1 ??= (Markdig.Extensions.DefinitionLists.DefinitionItem)Element16[1];
        private Markdig.Extensions.DefinitionLists.DefinitionTerm? _element16_1_0;
        internal Markdig.Extensions.DefinitionLists.DefinitionTerm Element16_1_0 => _element16_1_0 ??= (Markdig.Extensions.DefinitionLists.DefinitionTerm)Element16_1[0];
        private LiteralInline? _element16_1_0_0;
        internal LiteralInline Element16_1_0_0 => _element16_1_0_0 ??= (LiteralInline)Element16_1_0.Inline!.FirstChild!;
        private ParagraphBlock? _element16_1_1;
        internal ParagraphBlock Element16_1_1 => _element16_1_1 ??= (ParagraphBlock)Element16_1[1];
        private LiteralInline? _element16_1_1_0;
        internal LiteralInline Element16_1_1_0 => _element16_1_1_0 ??= (LiteralInline)Element16_1_1.Inline!.FirstChild!;
        private HeadingBlock? _element17;
        internal HeadingBlock Element17 => _element17 ??= (HeadingBlock)Document[17];
        private HtmlAttributes? _element17_Attributes;
        internal HtmlAttributes Element17_Attributes => _element17_Attributes ?? Element17.GetAttributes();
        private LiteralInline? _element17_0;
        internal LiteralInline Element17_0 => _element17_0 ??= (LiteralInline)Element17.Inline!.FirstChild!;
        private ParagraphBlock? _element18;
        internal ParagraphBlock Element18 => _element18 ??= (ParagraphBlock)Document[18];
        private LiteralInline? _element18_0;
        internal LiteralInline Element18_0 => _element18_0 ??= (LiteralInline)Element18.Inline!.FirstChild!;
        private CodeInline? _element18_1;
        internal CodeInline Element18_1 => _element18_1 ??= (CodeInline)Element18_0.NextSibling!;
        private LiteralInline? _element18_2;
        internal LiteralInline Element18_2 => _element18_2 ??= (LiteralInline)Element18.Inline!.LastChild!;
        private FencedCodeBlock? _element19;
        internal FencedCodeBlock Element19 => _element19 ??= (FencedCodeBlock)Document[19];
        private HtmlAttributes? _element19_Attributes;
        internal HtmlAttributes Element19_Attributes => _element19_Attributes ?? Element19.GetAttributes();
        private FencedCodeBlock? _element20;
        internal FencedCodeBlock Element20 => _element20 ??= (FencedCodeBlock)Document[20];
        private HtmlAttributes? _element20_Attributes;
        internal HtmlAttributes Element20_Attributes => _element20_Attributes ?? Element20.GetAttributes();
        private HeadingBlock? _element21;
        internal HeadingBlock Element21 => _element21 ??= (HeadingBlock)Document[21];
        private HtmlAttributes? _element21_Attributes;
        internal HtmlAttributes Element21_Attributes => _element21_Attributes ?? Element21.GetAttributes();
        private LiteralInline? _element21_0;
        internal LiteralInline Element21_0 => _element21_0 ??= (LiteralInline)Element21.Inline!.FirstChild!;
        private ParagraphBlock? _element22;
        internal ParagraphBlock Element22 => _element22 ??= (ParagraphBlock)Document[22];
        private LiteralInline? _element22_0;
        internal LiteralInline Element22_0 => _element22_0 ??= (LiteralInline)Element22.Inline!.FirstChild!;
        private LineBreakInline? _element22_1;
        internal LineBreakInline Element22_1 => _element22_1 ??= (LineBreakInline)Element22.Inline!.LastChild!;
        private HtmlAttributes? _element22_1_Attributes;
        internal HtmlAttributes Element22_1_Attributes => _element22_1_Attributes ?? Element22_1.GetAttributes();
        private HeadingBlock? _element23;
        internal HeadingBlock Element23 => _element23 ??= (HeadingBlock)Document[23];
        private HtmlAttributes? _element23_Attributes;
        internal HtmlAttributes Element23_Attributes => _element23_Attributes ?? Element23.GetAttributes();
        private LiteralInline? _element23_0;
        internal LiteralInline Element23_0 => _element23_0 ??= (LiteralInline)Element23.Inline!.FirstChild!;
        private ParagraphBlock? _element24;
        internal ParagraphBlock Element24 => _element24 ??= (ParagraphBlock)Document[24];
        private LiteralInline? _element24_0;
        internal LiteralInline Element24_0 => _element24_0 ??= (LiteralInline)Element24.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element24_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element24_1 => _element24_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element24_0.NextSibling!;
        private LiteralInline? _element24_2;
        internal LiteralInline Element24_2 => _element24_2 ??= (LiteralInline)Element24_1.NextSibling!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element24_3;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element24_3 => _element24_3 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element24_4.PreviousSibling!;
        private LiteralInline? _element24_4;
        internal LiteralInline Element24_4 => _element24_4 ??= (LiteralInline)Element24.Inline!.LastChild!;
        private HeadingBlock? _element25;
        internal HeadingBlock Element25 => _element25 ??= (HeadingBlock)Document[25];
        private HtmlAttributes? _element25_Attributes;
        internal HtmlAttributes Element25_Attributes => _element25_Attributes ?? Element25.GetAttributes();
        private LiteralInline? _element25_0;
        internal LiteralInline Element25_0 => _element25_0 ??= (LiteralInline)Element25.Inline!.FirstChild!;
        private ParagraphBlock? _element26;
        internal ParagraphBlock Element26 => _element26 ??= (ParagraphBlock)Document[26];
        private LiteralInline? _element26_0;
        internal LiteralInline Element26_0 => _element26_0 ??= (LiteralInline)Element26.Inline!.FirstChild!;
        private ParagraphBlock? _element27;
        internal ParagraphBlock Element27 => _element27 ??= (ParagraphBlock)Document[27];
        private LiteralInline? _element27_0;
        internal LiteralInline Element27_0 => _element27_0 ??= (LiteralInline)Element27.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteGroup? _element28;
        internal Markdig.Extensions.Footnotes.FootnoteGroup Element28 => _element28 ??= (Markdig.Extensions.Footnotes.FootnoteGroup)Document[28];
        private Markdig.Extensions.Footnotes.Footnote? _element28_0;
        internal Markdig.Extensions.Footnotes.Footnote Element28_0 => _element28_0 ??= (Markdig.Extensions.Footnotes.Footnote)Element28[0];
        private ParagraphBlock? _element28_0_0;
        internal ParagraphBlock Element28_0_0 => _element28_0_0 ??= (ParagraphBlock)Element28_0[0];
        private LiteralInline? _element28_0_0_0;
        internal LiteralInline Element28_0_0_0 => _element28_0_0_0 ??= (LiteralInline)Element28_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element28_0_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element28_0_0_1 => _element28_0_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element28_0_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.Footnote? _element28_1;
        internal Markdig.Extensions.Footnotes.Footnote Element28_1 => _element28_1 ??= (Markdig.Extensions.Footnotes.Footnote)Element28[1];
        private ParagraphBlock? _element28_1_0;
        internal ParagraphBlock Element28_1_0 => _element28_1_0 ??= (ParagraphBlock)Element28_1[0];
        private LiteralInline? _element28_1_0_0;
        internal LiteralInline Element28_1_0_0 => _element28_1_0_0 ??= (LiteralInline)Element28_1_0.Inline!.FirstChild!;
        private Markdig.Extensions.Footnotes.FootnoteLink? _element28_1_0_1;
        internal Markdig.Extensions.Footnotes.FootnoteLink Element28_1_0_1 => _element28_1_0_1 ??= (Markdig.Extensions.Footnotes.FootnoteLink)Element28_1_0.Inline!.LastChild!;
        
        internal MarkdownElementsOld(MarkdownDocument markdownDocument)
        {
            Document = markdownDocument;
        }
    }
}