//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InstallerTestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallerTestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.InstallerTestResources", typeof(InstallerTestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///# Module manifest for module &apos;module&apos;
        ///#
        ///# Generated by: 
        ///#
        ///# Generated on: 
        ///#
        ///
        ///@{
        ///
        ///# Script module or binary module file associated with this manifest.
        ///RootModule = &apos;Erwine.Leonard.T.PsNuGet.psm1&apos;
        ///
        ///# Version number of this module.
        ///ModuleVersion = &apos;1.0&apos;
        ///
        ///# ID used to uniquely identify this module
        ///GUID = &apos;9b04dc02-3745-43cb-9fe1-701423bfa859&apos;
        ///
        ///# Author of this module
        ///Author = &apos;&apos;
        ///
        ///# Company or vendor of this module
        ///CompanyName = &apos;Unknown&apos;
        ///
        ///# Copyright statement for this module
        ///Copyr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleManifest1 {
            get {
                return ResourceManager.GetString("ExampleManifest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ScriptBlock = {
        ///    $ScriptBlock = {
        ///        [DateTime]$Birthday = &apos;2/1/1967&apos;;
        ///        [DateTime]::Now
        ///    }
        ///    &amp;$ScriptBlock;
        ///    $Hash = @{
        ///        Object = [long]1, &apos;two&apos;, # Comment here? 
        ///            &apos;three&apos;
        ///        Separator = $null
        ///    }
        ///
        ///    Write-Host -Separator &quot;`t&quot; `
        ///		-ForegroundColor Black -Object @{ One = &apos;Two&apos;; Three = &apos;four&apos; }
        ///    Write-Host @Hash;
        ///    . c:\scripts\sample.ps1;
        ///    $(if ($var -eq $null) { &apos;Nully&apos; } else { &quot;Not!&quot; });
        ///    [ordered]@{a=1; b=2; c=3}
        ///    &quot;This i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScriptParseTest {
            get {
                return ResourceManager.GetString("ScriptParseTest", resourceCulture);
            }
        }
    }
}
