//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LteDevClr {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlSchemas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlSchemas() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LteDevClr.XmlSchemas", typeof(XmlSchemas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://schemas.microsoft.com/maml/dev/2004/10&quot; xmlns:doc=&quot;http://schemas.microsoft.com/maml/internal&quot; xmlns:maml=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns:dev=&quot;http://schemas.microsoft.com/maml/dev/2004/10&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; blockDefault=&quot;#all&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!-- Schema documentation --&gt;
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;This schema describes [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string developer {
            get {
                return ResourceManager.GetString("developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://schemas.microsoft.com/maml/dev/command/2004/10&quot; xmlns:doc=&quot;http://schemas.microsoft.com/maml/internal&quot; xmlns:maml=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns:dev=&quot;http://schemas.microsoft.com/maml/dev/2004/10&quot; xmlns:command=&quot;http://schemas.microsoft.com/maml/dev/command/2004/10&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; blockDefault=&quot;#all&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!-- Sche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string developerCommand {
            get {
                return ResourceManager.GetString("developerCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://schemas.microsoft.com/maml/dev/managed/2004/10&quot; xmlns:doc=&quot;http://schemas.microsoft.com/maml/internal&quot; xmlns:maml=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns:dev=&quot;http://schemas.microsoft.com/maml/dev/2004/10&quot; xmlns:managed=&quot;http://schemas.microsoft.com/maml/dev/managed/2004/10&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; blockDefault=&quot;#all&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!-- Sche [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string developerManaged {
            get {
                return ResourceManager.GetString("developerManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://msh&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;unqualified&quot; attributeFormDefault=&quot;unqualified&quot; xml:lang=&quot;en&quot;&gt;
        ///  &lt;!-- Schema documentation --&gt;
        ///  &lt;annotation&gt;
        ///    &lt;documentation&gt;This schema represents the root document element for PowerShell help files.&lt;/documentation&gt;
        ///  &lt;/annotation&gt;
        ///  &lt;import schemaLocation=&quot;maml.xsd&quot; namespace=&quot;http://schemas.microsoft.com/maml/2004/10&quot;/&gt;
        ///  &lt;import schemaLocation=&quot;developer.xsd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string helpItems {
            get {
                return ResourceManager.GetString("helpItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;schema targetNamespace=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns:doc=&quot;http://schemas.microsoft.com/maml/internal&quot; xmlns:maml=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot; attributeFormDefault=&quot;unqualified&quot; blockDefault=&quot;#all&quot; xml:lang=&quot;en&quot;&gt;
        ///    &lt;!-- Schema documentation --&gt;
        ///    &lt;annotation&gt;
        ///        &lt;documentation&gt;This schema describes MAML (Microsoft Assistance Markup Language). MAML is  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maml {
            get {
                return ResourceManager.GetString("maml", resourceCulture);
            }
        }
    }
}
