//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XmlHelp {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlHelp() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTests.XmlHelp", typeof(XmlHelp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.GDIPlus&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Erwine.Leonard.T.GDIPlus.Collections.Synchronized.NonNullSynchronizedList`1&quot;&gt;
        ///            &lt;summary&gt;
        ///            Represents a syncrhonized (thread-safe), strongly typed list of class objects whose elements are not permitted to have null values.
        ///            &lt;/summary&gt;
        ///            &lt;typeparam name=&quot;T&quot;&gt;The type of elements in the list.&lt;/typeparam&gt;
        ///        &lt;/mem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_GDIPlus {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_GDIPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.IOUtilityLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:IOUtility.EncodeRegexReplaceHandler&quot;&gt;
        ///            &lt;summary&gt;
        ///            Encodes text according to a specific pattern.
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:IOUtility.EncodeRegexReplaceHandler.#ctor(System.String,System.Text.RegularExpressions.RegexOptions)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Initialize new &lt;see cref=&quot;T:IOU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_IOUtilityLib {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_IOUtilityLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.LteDevLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;!-- Badly formed XML comment ignored for member &quot;P:LteDev.HelpXml.CmdletHelpExporter.CurrentHelpElement&quot; --&gt;
        ///        &lt;member name=&quot;T:LteDev.Commands.Get_PSHelpXml&quot;&gt;
        ///            &lt;summary&gt;
        ///            Generates PowerShell help file from module information.
        ///            &lt;/summary&gt;
        ///            &lt;description&gt;
        ///            Gets information from the PowerShell module, including [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_LteDevLib {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_LteDevLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.Speech&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Speech.Commands.ConvertTo_PromptBuilder&quot;&gt;
        ///            &lt;summary&gt;
        ///            Converts plain text to a &lt;seealso cref=&quot;T:System.Speech.Synthesis.PromptBuilder&quot;/&gt;.
        ///            &lt;/summary&gt;
        ///            &lt;remarks&gt;
        ///            &lt;para type=&quot;description&quot;&gt;Creates a new &lt;seealso cref=&quot;T:System.Speech.Synthesis.PromptBuilder&quot;/&gt; from the provided plain text or appends text  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_Speech {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_Speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.WPFLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:Erwine.Leonard.T.WPF.Commands.Assert_ValidXamlMarkup&quot;&gt;
        ///            &lt;summary&gt;
        ///            Asserts validity of XAML markup.
        ///            &lt;/summary&gt;
        ///            &lt;remarks&gt;Writes an error if the XML Markup is not valid.&lt;/remarks&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;T:Erwine.Leonard.T.WPF.Commands.New_WpfWindow&quot;&gt;
        ///            &lt;summary&gt;
        ///            New-WpfWin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_WPFLib {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_WPFLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;Erwine.Leonard.T.XmlUtilityLib&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;T:XmlUtility.LoadableBinaryResource`1&quot;&gt;
        ///            &lt;summary&gt;
        ///            
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:XmlUtility.LoadableBinaryResource`1.#ctor(System.Uri)&quot;&gt;
        ///            &lt;summary&gt;
        ///            
        ///            &lt;/summary&gt;
        ///        &lt;/member&gt;
        ///        &lt;member name=&quot;M:XmlUtility.LoadableBinaryResource`1.CreateTarget&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Erwine_Leonard_T_XmlUtilityLib {
            get {
                return ResourceManager.GetString("Erwine_Leonard_T_XmlUtilityLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;speak version=&quot;1.0&quot; xmlns=&quot;http://www.w3.org/2001/10/synthesis&quot; xml:lang=&quot;en-US&quot;&gt;
        ///  &lt;prosody rate=&quot;fast&quot;&gt;
        ///  &lt;voice gender=&quot;male&quot; age=&quot;30&quot;&gt;
        ///    1.1 Identifying Components of Motherboards
        ///  &lt;/voice&gt;
        ///  &lt;voice gender=&quot;female&quot; age=&quot;30&quot;&gt;
        ///    The spine of the computer is the motherboard, otherwise known as the system board or mainboard.
        ///    This is the printed circuit board (&lt;say-as interpret-as=&quot;characters&quot;&gt;PCB&lt;/say-as&gt;), which is a conductive series of pathways laminated to a nonconductive substrate that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleSSML {
            get {
                return ResourceManager.GetString("ExampleSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;helpItems xmlns=&quot;http://msh&quot; schema=&quot;maml&quot;&gt;
        ///  &lt;!-- Updatable Help Version 4.0.2.0 --&gt;
        ///  &lt;command:command xmlns:maml=&quot;http://schemas.microsoft.com/maml/2004/10&quot; xmlns:command=&quot;http://schemas.microsoft.com/maml/dev/command/2004/10&quot; xmlns:dev=&quot;http://schemas.microsoft.com/maml/dev/2004/10&quot; xmlns:MSHelp=&quot;http://msdn.microsoft.com/mshelp&quot;&gt;
        ///    &lt;command:details&gt;
        ///      &lt;command:name&gt;Add-BitsFile&lt;/command:name&gt;
        ///      &lt;maml:description&gt;
        ///        &lt;maml:para&gt;Adds one or mo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft_BackgroundIntelligentTransfer_Management_dll_Help {
            get {
                return ResourceManager.GetString("Microsoft_BackgroundIntelligentTransfer_Management_dll_Help", resourceCulture);
            }
        }
    }
}
